services:
  reimbursement:
    image: mysql/spring-boot-project1
    ports:
      - 8080:8080
    environment:
      - MY_PORT=8080
      - DB_URL=jdbc:mysql://db:3306/Project1
      - DB_USERNAME=admin
      - DB_PASSWORD=password
    depends_on:
      - db
  emails:
    image: mysql/spring-boot-project1-email
    ports:
      - 8081:8081
    environment:
      - MY_PORT=8080
      - DB_URL=jdbc:mysql://db:3306/Project1
      - DB_USERNAME=admin
      - DB_PASSWORD=password
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
#      - MY_PORT=3307
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Project1
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
