#services:
#  web:
#    image: mysql/spring-boot-project1-email
#    container_name: my-spring-boot-project1-email-api
#    restart: always
#    environment:
#      - MY_PORT=8081
#      - DB_URL=jdbc:mysql://db:3306/Project1
#      - DB_USERNAME=admin
#      - DB_PASSWORD=password
#    ports:
#      - 8081:8081
#    depends_on:
#      - db
#  db:
#    image: mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=Project1
#      - MYSQL_USER=admin
#      - MYSQL_PASSWORD=password
