server:
#  servlet:
#    context-path: /reimbursement

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://35.226.45.187:3306/project1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true